version: 2.1
jobs:
  build:
    working_directory: ~/dev/ionic-test
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

    
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

  
      - persist_to_workspace:
          root: ~/dev/ionic-test
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  android-build-and-test:
    working_directory: ~/dev/ionic-test
    docker:
      - image: cimg/android:2022.01.1-node
    steps:
      - checkout:
          path: ~/dev/ionic-test
          
      - attach_workspace:
          at: ~/demo-react-native

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}   

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
            

      - run:
         name: install-packages
         command: | 
         
          npm install      

      - run:
          name: install ionic cli
          command: |
            sudo npm install -g @ionic/cli
            sudo which ionic
            sudo ionic build
            sudo ionic cap add android
            sudo ionic cap copy android 
            sudo ionic cap copy
            sudo ionic cap sync
      - run:
          name: list files
          command: ls -l                 

      # - run:
      #     name: chmod permissions
          
      #     command: |
      #      cd android &&  chmod +x ./gradlew

      
     
           
      - run:
          name: Run Lindt Test
          command: |
            find .
             cd android && sudo ./gradlew lint test    

      - store_artifacts:
          path: android/app/build/reports
          destination: reports
      - store_test_results:
          path: android/app/build/test-results   

      - run:
          name: Assemble release build
          command: |
            find .
            cd android &&  ./gradlew bundleRelease
            find .
      - store_artifacts:
        
          path: android/app/build/outputs/bundle/release
      
      - run:
          name: Assemble release Apk 
          command: |
            find .
            cd android &&  sudo ./gradlew assembleRelease
            find .
      - store_artifacts:
        
          path: android/app/build/outputs/apk/release

 

workflows:
  ionic-test:
    jobs:
      - build
      - android-build-and-test:
          requires:
            - build
            